### ISSUE TITLE
User profile entry page

### ISSUE THREAD

**Issue by thejoeejoee** [esnvutbrno/buena-fiesta#157]
* currently, user profile page entry is empty
* based on the information in other tabs, decide what we want to include on the entry page
* registration date? some basic statistics?
* [view](https://github.com/esnvutbrno/buena-fiesta/blob/87ca389139263b41339f68c84d1c086c9acfa23c/fiesta/apps/accounts/views/profile.py#L18-L23) and [template](https://github.com/esnvutbrno/buena-fiesta/blob/87ca389139263b41339f68c84d1c086c9acfa23c/fiesta/apps/accounts/templates/accounts/user_profile/detail.html#L1-L1)

<img width="1441" alt="image" src="https://github.com/esnvutbrno/buena-fiesta/assets/6154740/ef0d918e-aab6-46b9-bbc2-22d5fc72482c">

**Comment by chepurisaivignesh** [comment]
### My Suggestions

- [ ] Profile picture can be removed from navbar and the profile page can show the image in an enlarged view.
- [ ] Name or Username of the User 
- [ ] Bio / interests section
- [ ] Social media handle links of the user

**Comment by chLynda** [comment]
Hello i would like to contribute on your project ,
can I?

**Comment by thejoeejoee** [comment]
@chepurisaivignesh @chLynda feel free to contribute with PR ✌️
