### ISSUE TITLE
Fix empty dashboard block for buddy system

### ISSUE THREAD

**Issue by thejoeejoee** [esnvutbrno/buena-fiesta#160]
* hide the `My Buddies` sub-block OR display CTA for buddy matching
* [block template](https://github.com/esnvutbrno/buena-fiesta/blob/87ca389139263b41339f68c84d1c086c9acfa23c/fiesta/apps/buddy_system/templates/buddy_system/dashboard_block.html#L50-L84)

<img width="1857" alt="image" src="https://github.com/esnvutbrno/buena-fiesta/assets/6154740/aaf382f0-9429-4fe5-810e-3037d85cc38e">

**Comment by petrceska** [comment]
So it should be hidden if member does not have a buddy and show buddies when there are some competed matches, right? 

btw.
If I click on **SHOW WAITING REQUESTS** it returns: 
https://esnvutbrno.fiesta.test/buddy-system/matching-requests
ESN VUT Brno
Buddy System: enabled
ESN VUT Brno: Admin kyperas (Confirmed)
2023-06-26T19:35:09.698468+00:00

What am I doing wrong?

**Comment by thejoeejoee** [comment]
@petrceska One option is to hide that half of block it completely. But I was thinking in more "interactive" way, would be nice to display a CTA button with "get first buddy" or smth like that. Up to you, choose what makes it better.

The URL `https://esnvutbrno.fiesta.test/buddy-system/matching-requests` is fine, the content is not. What template does it render? (the DJT shows it, it should be `fiesta/apps/buddy_system/templates/buddy_system/matching_requests.html`) Also, is your BuddySystemConfiguration allowing [matching by members](https://github.com/esnvutbrno/buena-fiesta/blob/develop/fiesta/apps/buddy_system/views/matching.py#L32)?
