### ISSUE TITLE
Profile status completeness on dashboard block

### ISSUE THREAD

**Issue by thejoeejoee** [esnvutbrno/buena-fiesta#161]
* currently, the percentage is static
* the value should follow the real completness of profile
* [template](https://github.com/esnvutbrno/buena-fiesta/blob/87ca389139263b41339f68c84d1c086c9acfa23c/fiesta/apps/accounts/templates/accounts/dashboard_block.html#L28-L28)
* be aware, `UserProfileForm` is dynamic form constructed from configurations of all sections, in which is specific user in membership
* so the solution would be:
  1. construct the form via `UserProfileForm.for_user(user: User)`
  2. fill the form with instance of user
  3. compute the percentage of filled and unfilled fields in the form (not all fields, some defining subset of them)
  4. map the value to the color and display it

![image](https://github.com/esnvutbrno/buena-fiesta/assets/6154740/93d30618-7b7e-46e2-a034-66017cf76a9e)

**Comment by punndcoder28** [comment]
Hi @thejoeejoee I would love to pick up the issue if not already assigned.

**Comment by thejoeejoee** [comment]
@punndcoder28 feel free to contribute with PR ✌️

**Comment by punndcoder28** [comment]
Thanks. Will be contributing a PR soon. I was following the instructions in the `README.md` file to setup up the development server locally to build and test but have hit a road block and would help a love if I can get more information. I have followed all the instructions to set up the development server but I am unable to access the the local website on `http://fiesta.test/`. I did not encounter any errors while setting up the environment. Thanks in advance

**Comment by thejoeejoee** [comment]
@punndcoder28 What OS are you using? Is `fiesta.test` pointing to your localhost? What's result of `dig fiesta.test` or `nslookup fiesta.test`? Does `curl fiesta.test` outputs something after starting up the docker compose?

**Comment by punndcoder28** [comment]
Thanks for the reply.
1. I am use `macos 13.3.1`
2. How can I confirm if `fiesta.test` is pointing to my local host? Is it the same as `ROOT_DOMAIN=fiesta.test`
3. Running `nslookup fiesta.test` outputs 
```
Server:		192.168.0.1
Address:	192.168.0.1#53

** server can't find fiesta.test: NXDOMAIN
```
4. Running `curl fiesta.test` returns the following `curl: (6) Could not resolve host: fiesta.test`

Is there something I might have missed during the setup process because this seems like the local domain is not setup the right way

**Comment by thejoeejoee** [comment]
@punndcoder28 the 7th point in README is probably not clear; I'll rewrite it. 

Yep, the `ROOT_DOMAIN` is properly set, you've to ensure your system to resolve `fiesta.test` to localhost. So if you're using docker directly on your system, you must add record to `/etc/hosts` like this:

```
127.0.0.1	fiesta.test
```

If you're using `colima` or other solution with docker in VM, add IP of the IP instead of `127.0.0.1`.

**Comment by punndcoder28** [comment]
I am using the docker application directly on my machine. I just saw the contents of `/etc/hosts` and there is a record
```
127.0.0.1	       localhost
```
already on the file. Should I be replacing this with what you have suggested?

**Comment by thejoeejoee** [comment]
@punndcoder28 put another one line there for `fiesta.test`

**Comment by punndcoder28** [comment]
Don't know if it is the right place. On running the project locally, the styles seem to not be loading, and the landing page screen has out-of-size icons. Attaching a picture for better visibility

<img width="1440" alt="Screenshot 2023-06-03 at 11 32 27 PM" src="https://github.com/esnvutbrno/buena-fiesta/assets/32433964/320cadf4-3397-45f5-ac8f-4d559ccb3fd9">

**Comment by thejoeejoee** [comment]
@punndcoder28 looks promising! probably `webpack.fiesta.test` has to be also in the hosts file:

```
127.0.0.1	fiesta.test webpack.fiesta.test
```

**Comment by punndcoder28** [comment]
Thanks. The above suggestions work. Can I also update the `README.md` to be more clearer to help set up things for contributors?

**Comment by punndcoder28** [comment]
Hi @thejoeejoee I went through the code which generates the `form_class`, specifically the line 
`form_class = UserProfileForm.for_user(user=profile.user)` in `user_profile_state_synchronizer.py`. Would I be computing the percentage of the completed profile from this? I want to include the following user profile fields which can be considered as the required fields of the profile
```
nationality
gender
home_university
home_faculty
guest_faculty
picture
interests
```

I am also thinking along the line where I will need to update the user model to hold the `percentage_complete` field which will hold the percent completed which can then used to display the right color mapping in the profile section

**Comment by punndcoder28** [comment]
Hi @thejoeejoee I went through the code which generates the `form_class`, specifically the line 
`form_class = UserProfileForm.for_user(user=profile.user)` in `user_profile_state_synchronizer.py`. Would I be computing the percentage of the completed profile from this? I want to include the following user profile fields which can be considered as the required fields for the profile
```
nationality
gender
home_university
home_faculty
guest_faculty
phone_number
preferences
interests
```
I think we can exclude the following fields since they are social media files
```
picture
facebook
instagram
telegram
whatsapp
```
I am also thinking along the line where I will need to update the user model to hold the `percentage_complete` field which will hold the percent completed which can then used to display the right color mapping in the profile section. Would love to hear your thoughts

**Comment by punndcoder28** [comment]
@thejoeejoee I was trying to complete my profile to test out my code changes but I am running in the error which is raised by the following piece of code
```
         if not (bool(self.home_university) ^ bool(self.home_faculty)):
            raise ValidationError(
                {
                    "home_university": _(
                        # TODO: weird, basically it's exactly one of these
                        "At least one from home university/faculty has to be set."
                    )
                }
            )
```
I am unable to understand what this exactly checks for.

**Comment by thejoeejoee** [comment]
@punndcoder28 this validation checks that home_university XOR home_faculty is set; for international students we need home_uni and guest_faculty (which does have relation to uni), and for local members only home_faculty (which does have relation to uni). So it's kinda weird, probably the validation could be done other way.

Regarding the fields for the completness: `preferences` is just TODO field, not doing anything, I wouldn't include it. The picture should be definitiely in the formula for the completness, and from the social profiles I'd say you've to fill at least half from them to get full points.

**Comment by punndcoder28** [comment]
Thanks. I think there should be some way where we can make it much more readable. I have two more questions
1. How are we deciding if a student is an international student or a domestic student
2. I am getting the validation error even when I am filling out all the university and faculty fields
3. How exactly do I navigate to the `dashboard` section. I tried to access the `dashboard` section based on the URL from the issue description image but the website asks me to choose a section when I can see no options to choose. Attaching a image for easier understanding

![Screenshot 2023-06-10 at 23-24-11 Buena Fiesta](https://github.com/esnvutbrno/buena-fiesta/assets/32433964/7d4945ff-21cc-4193-891e-86cb98502134)

**Comment by punndcoder28** [comment]
Hi @thejoeejoee any updates on the above questions? Thanks!

**Comment by thejoeejoee** [comment]
@punndcoder28 Sorry for the delay, regarding your questions:

1. Depends on the `SectionMembership.role` field -- user does have multiple memberships, but only single one is active when the page is shown, and it's stored in `request.membership` by the `UserMembershipMiddleware`
2. THe validation is kinda tricky here and ready for some revision, but it's meant to be filled with home_uni+guest_faculty for international students, and only home_faculty for local students. The validation is done here in [UserProfileForm](https://github.com/esnvutbrno/buena-fiesta/blob/47a77a33079ea4db65a6e7a1e6a789ab2b3c139d/fiesta/apps/accounts/models/profile.py#L184-L195). 
3. You've to add a Section with active Dashboard Plugin and after that you should be able to choose section space with dashboard.

**Comment by punndcoder28** [comment]
Thanks for the reply. Can you help me understand where this Dashboard plugin exists and what the steps are to add it to be able to view the sections in dashboard page. I was unable to figure out how I can add the plugin. Thanks again!
