### ISSUE TITLE
Matched buddies are not showed

### ISSUE THREAD

**Issue by petrceska** [esnvutbrno/buena-fiesta#184]
BUDDY block is empty even though I just matched with a buddy

![Image](https://github.com/esnvutbrno/buena-fiesta/assets/44273500/b83c6c52-1e24-4f0a-bf3f-db2c8b96848a)

**Comment by thejoeejoee** [comment]
probably related to #160, the dashboard_block for local members is bugged with connection to [this](https://github.com/esnvutbrno/buena-fiesta/blob/develop/fiesta/apps/buddy_system/templatetags/buddy_system.py#L73-L81) template tag for loading matched buddies; thanks for looking onto that

**Comment by shobhit9957** [comment]
I would like to contribute. /attempt #184
can you give me directions on how can I contribute to this project

**Comment by petrceska** [comment]
already fixed in #196
